apiVersion: v1
kind: Service
metadata:
  name: candle-frontend-service
spec:
  selector:
    app: candle-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # 외부 접근을 위한 설정
